# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-03 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='component',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='事件子项'),
        ),
        migrations.AlterField(
            model_name='server',
            name='os_distribution',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='发行版本'),
        ),
    ]
