# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-05 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_auto_20170703_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disk',
            name='slot',
            field=models.IntegerField(verbose_name='插槽位'),
        ),
    ]
