# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-05 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0004_auto_20170705_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disk',
            name='slot',
            field=models.IntegerField(verbose_name='插槽位'),
        ),
    ]
